-- MySQL Script generated by MySQL Workbench
-- Sun Mar 12 17:26:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`item` ;

CREATE TABLE IF NOT EXISTS `sistema`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`order` ;

CREATE TABLE IF NOT EXISTS `sistema`.`order` (
  `name` VARCHAR(45) NOT NULL,
  `item` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `item_idx` (`item` ASC) VISIBLE,
  CONSTRAINT `item`
    FOREIGN KEY (`item`)
    REFERENCES `sistema`.`item` (`id`),
  CONSTRAINT `name`
    FOREIGN KEY (`name`)
    REFERENCES `sistema`.`user` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema`.`user` ;

CREATE TABLE IF NOT EXISTS `sistema`.`user` (
  `name` VARCHAR(45) NOT NULL,
  `admin` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
